#!/usr/bin/env python3
"""
VHDL Testbench Generator

Automatically generates comprehensive testbenches from VHDL entity declarations.
"""

import re
import argparse
from pathlib import Path
from typing import List, Dict, Tuple


class VHDLTestbenchGenerator:
    """Generate VHDL testbenches from entity declarations"""
    
    def __init__(self, vhdl_file: Path):
        self.vhdl_file = vhdl_file
        self.entity_name = None
        self.ports = []
        self.generics = []
        
    def parse_entity(self) -> bool:
        """Parse entity declaration from VHDL file"""
        with open(self.vhdl_file, 'r') as f:
            content = f.read()
        
        # Extract entity name
        entity_match = re.search(r'entity\s+(\w+)\s+is', content, re.IGNORECASE)
        if not entity_match:
            print("❌ Could not find entity declaration")
            return False
        
        self.entity_name = entity_match.group(1)
        
        # Extract ports
        port_section = re.search(r'port\s*\((.*?)\);', content, re.IGNORECASE | re.DOTALL)
        if port_section:
            self.ports = self._parse_ports(port_section.group(1))
        
        # Extract generics if present
        generic_section = re.search(r'generic\s*\((.*?)\);', content, re.IGNORECASE | re.DOTALL)
        if generic_section:
            self.generics = self._parse_generics(generic_section.group(1))
        
        return True
    
    def _parse_ports(self, port_text: str) -> List[Dict]:
        """Parse port declarations"""
        ports = []
        
        # Split by semicolon
        declarations = port_text.split(';')
        
        for decl in declarations:
            decl = decl.strip()
            if not decl:
                continue
            
            # Parse: name : direction type
            match = re.match(r'(\w+)\s*:\s*(in|out|inout)\s+(.+)', decl, re.IGNORECASE)
            if match:
                ports.append({
                    'name': match.group(1),
                    'direction': match.group(2).lower(),
                    'type': match.group(3).strip()
                })
        
        return ports
    
    def _parse_generics(self, generic_text: str) -> List[Dict]:
        """Parse generic declarations"""
        generics = []
        
        declarations = generic_text.split(';')
        
        for decl in declarations:
            decl = decl.strip()
            if not decl:
                continue
            
            # Parse: name : type := default
            match = re.match(r'(\w+)\s*:\s*(\w+)\s*:=\s*(.+)', decl, re.IGNORECASE)
            if match:
                generics.append({
                    'name': match.group(1),
                    'type': match.group(2),
                    'default': match.group(3).strip()
                })
        
        return generics
    
    def generate_testbench(self) -> str:
        """Generate complete testbench"""
        tb = []
        
        # Header
        tb.append("-- Testbench automatically generated for " + self.entity_name)
        tb.append("-- Generated by VHDL Testbench Generator")
        tb.append("")
        
        # Library declarations
        tb.append("library ieee;")
        tb.append("use ieee.std_logic_1164.all;")
        tb.append("use ieee.numeric_std.all;")
        tb.append("")
        
        # Entity declaration (testbench has no ports)
        tb_name = f"tb_{self.entity_name}"
        tb.append(f"entity {tb_name} is")
        tb.append("end entity " + tb_name + ";")
        tb.append("")
        
        # Architecture
        tb.append(f"architecture behavioral of {tb_name} is")
        tb.append("")
        
        # Component declaration
        tb.append("  -- Component declaration")
        tb.append(f"  component {self.entity_name} is")
        
        # Generics if present
        if self.generics:
            tb.append("    generic (")
            for i, gen in enumerate(self.generics):
                comma = ";" if i < len(self.generics) - 1 else ""
                tb.append(f"      {gen['name']} : {gen['type']} := {gen['default']}{comma}")
            tb.append("    );")
        
        # Ports
        tb.append("    port (")
        for i, port in enumerate(self.ports):
            comma = ";" if i < len(self.ports) - 1 else ""
            tb.append(f"      {port['name']} : {port['direction']} {port['type']}{comma}")
        tb.append("    );")
        tb.append(f"  end component {self.entity_name};")
        tb.append("")
        
        # Signal declarations
        tb.append("  -- Signal declarations")
        for port in self.ports:
            init_value = self._get_init_value(port['type'])
            tb.append(f"  signal {port['name']}_tb : {port['type']} := {init_value};")
        
        # Clock and control signals
        if self._has_clock():
            tb.append("  signal clk_period : time := 10 ns;")
            tb.append("  signal sim_done : boolean := false;")
        
        tb.append("")
        tb.append("begin")
        tb.append("")
        
        # DUT instantiation
        tb.append("  -- Device Under Test (DUT)")
        tb.append(f"  dut : {self.entity_name}")
        if self.generics:
            tb.append("    generic map (")
            for i, gen in enumerate(self.generics):
                comma = "," if i < len(self.generics) - 1 else ""
                tb.append(f"      {gen['name']} => {gen['default']}{comma}")
            tb.append("    )")
        
        tb.append("    port map (")
        for i, port in enumerate(self.ports):
            comma = "," if i < len(self.ports) - 1 else ""
            tb.append(f"      {port['name']} => {port['name']}_tb{comma}")
        tb.append("    );")
        tb.append("")
        
        # Clock generation if needed
        clk_port = self._get_clock_port()
        if clk_port:
            tb.append("  -- Clock generation")
            tb.append(f"  clk_process : process")
            tb.append("  begin")
            tb.append("    while not sim_done loop")
            tb.append(f"      {clk_port}_tb <= '0';")
            tb.append("      wait for clk_period / 2;")
            tb.append(f"      {clk_port}_tb <= '1';")
            tb.append("      wait for clk_period / 2;")
            tb.append("    end loop;")
            tb.append("    wait;")
            tb.append("  end process clk_process;")
            tb.append("")
        
        # Stimulus process
        tb.append("  -- Stimulus process")
        tb.append("  stim_process : process")
        tb.append("  begin")
        tb.append("    -- Initialize inputs")
        
        # Reset if present
        rst_port = self._get_reset_port()
        if rst_port:
            tb.append(f"    {rst_port}_tb <= '1';")
            if clk_port:
                tb.append("    wait for clk_period * 2;")
                tb.append(f"    {rst_port}_tb <= '0';")
                tb.append("    wait for clk_period;")
            else:
                tb.append("    wait for 20 ns;")
                tb.append(f"    {rst_port}_tb <= '0';")
                tb.append("    wait for 10 ns;")
        else:
            tb.append("    wait for 20 ns;")
        
        tb.append("")
        tb.append("    -- Test case 1: Basic functionality")
        tb.append("    report \"Starting test case 1\";")
        
        # Generate basic test vectors
        input_ports = [p for p in self.ports if p['direction'] == 'in' and p['name'] not in ['clk', 'clock', 'rst', 'reset']]
        if input_ports:
            for port in input_ports:
                test_value = self._get_test_value(port['type'])
                tb.append(f"    {port['name']}_tb <= {test_value};")
            
            if clk_port:
                tb.append("    wait for clk_period * 5;")
            else:
                tb.append("    wait for 50 ns;")
        
        tb.append("")
        tb.append("    -- TODO: Add more test cases here")
        tb.append("    -- Test edge cases, boundary conditions, etc.")
        tb.append("")
        tb.append("    -- End simulation")
        tb.append("    report \"Testbench completed\";")
        if clk_port:
            tb.append("    sim_done <= true;")
        tb.append("    wait;")
        tb.append("  end process stim_process;")
        tb.append("")
        
        # Assertions/checking process for outputs
        output_ports = [p for p in self.ports if p['direction'] == 'out']
        if output_ports:
            tb.append("  -- Output checking (add assertions as needed)")
            tb.append("  check_process : process")
            tb.append("  begin")
            tb.append("    wait for 100 ns;")
            tb.append("    -- TODO: Add assertions to check outputs")
            for port in output_ports:
                tb.append(f"    -- Example: assert {port['name']}_tb = expected_value")
                tb.append(f"    --   report \"Output {port['name']} mismatch\" severity error;")
            tb.append("    wait;")
            tb.append("  end process check_process;")
            tb.append("")
        
        tb.append(f"end architecture behavioral;")
        
        return '\n'.join(tb)
    
    def _get_init_value(self, port_type: str) -> str:
        """Get initialization value for signal type"""
        port_type = port_type.lower()
        if 'std_logic' in port_type:
            return "'0'"
        elif 'integer' in port_type or 'unsigned' in port_type or 'signed' in port_type:
            return "0"
        elif 'boolean' in port_type:
            return "false"
        else:
            return "'0'"
    
    def _get_test_value(self, port_type: str) -> str:
        """Get test value for signal type"""
        port_type = port_type.lower()
        if 'std_logic' in port_type:
            return "'1'"
        elif 'unsigned' in port_type or 'signed' in port_type:
            return "x\"0F\""
        elif 'integer' in port_type:
            return "42"
        elif 'boolean' in port_type:
            return "true"
        else:
            return "'1'"
    
    def _has_clock(self) -> bool:
        """Check if entity has clock signal"""
        clock_names = ['clk', 'clock', 'clk_i']
        return any(p['name'].lower() in clock_names for p in self.ports)
    
    def _get_clock_port(self) -> str:
        """Get clock port name"""
        clock_names = ['clk', 'clock', 'clk_i']
        for port in self.ports:
            if port['name'].lower() in clock_names:
                return port['name']
        return None
    
    def _get_reset_port(self) -> str:
        """Get reset port name"""
        reset_names = ['rst', 'reset', 'rst_i', 'rst_n', 'reset_n']
        for port in self.ports:
            if port['name'].lower() in reset_names:
                return port['name']
        return None


def main():
    parser = argparse.ArgumentParser(description='Generate VHDL testbench')
    parser.add_argument('vhdl_file', help='VHDL source file')
    parser.add_argument('--output', '-o', help='Output testbench file (default: tb_<entity>.vhd)')
    
    args = parser.parse_args()
    
    vhdl_file = Path(args.vhdl_file)
    if not vhdl_file.exists():
        print(f"❌ File not found: {vhdl_file}")
        return 1
    
    # Generate testbench
    generator = VHDLTestbenchGenerator(vhdl_file)
    if not generator.parse_entity():
        return 1
    
    testbench_code = generator.generate_testbench()
    
    # Determine output file
    if args.output:
        output_file = Path(args.output)
    else:
        output_file = vhdl_file.parent / f"tb_{generator.entity_name}.vhd"
    
    # Write testbench
    with open(output_file, 'w') as f:
        f.write(testbench_code)
    
    print(f"✅ Generated testbench: {output_file}")
    print(f"   Entity: {generator.entity_name}")
    print(f"   Ports: {len(generator.ports)}")
    if generator.generics:
        print(f"   Generics: {len(generator.generics)}")
    
    return 0


if __name__ == '__main__':
    exit(main())
