#!/usr/bin/env python3
"""
Generate VHDL package with Iris dataset for binary classification.

This script:
1. Loads the Iris dataset using scikit-learn
2. Converts to binary classification (Setosa vs Non-Setosa)
3. Normalizes features to [0,1] range
4. Converts to Q2.13 fixed-point format
5. Generates VHDL package with 30 samples
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler


def float_to_q2_13(value):
    """
    Convert a float value to Q2.13 fixed-point format.

    Q2.13 format: 2 integer bits, 13 fractional bits (16 bits total)
    Range: [-2, 2) with resolution of 1/8192

    Args:
        value: Float value in range [0, 1]

    Returns:
        Integer representation in Q2.13 format
    """
    # Scale by 2^13 = 8192
    scaled = int(round(value * 8192))

    # Clamp to valid range for Q2.13: [-16384, 16383]
    # For normalized [0,1] values, this maps to [0, 8192]
    if scaled > 16383:
        scaled = 16383
    elif scaled < -16384:
        scaled = -16384

    return scaled


def generate_vhdl_package(features, labels, output_file='iris_dataset_small_pkg.vhd'):
    """
    Generate VHDL package with Iris dataset.

    Args:
        features: Array of shape (n_samples, n_features) with normalized values
        labels: Array of shape (n_samples,) with binary labels
        output_file: Output VHDL file name
    """
    num_samples = features.shape[0]
    num_features = features.shape[1]

    # Convert features to Q2.13 format
    features_q2_13 = np.zeros_like(features, dtype=int)
    for i in range(num_samples):
        for j in range(num_features):
            features_q2_13[i, j] = float_to_q2_13(features[i, j])

    # Convert labels to Q2.13 format (0 for Setosa, 8192 for Non-Setosa)
    labels_q2_13 = np.array([0 if label == 0 else 8192 for label in labels])

    # Generate VHDL code
    vhdl_code = []

    # Header
    vhdl_code.append("-- VHDL Package: Iris Dataset (Binary Classification)")
    vhdl_code.append("-- Auto-generated by generate_iris_vhdl.py")
    vhdl_code.append("-- Dataset: Setosa vs Non-Setosa")
    vhdl_code.append("-- Format: Q2.13 fixed-point")
    vhdl_code.append("")
    vhdl_code.append("library IEEE;")
    vhdl_code.append("use IEEE.STD_LOGIC_1164.ALL;")
    vhdl_code.append("use IEEE.NUMERIC_STD.ALL;")
    vhdl_code.append("")

    # Package declaration
    vhdl_code.append("package iris_dataset_small_pkg is")
    vhdl_code.append("")

    # Constants
    vhdl_code.append(f"    constant NUM_SAMPLES  : integer := {num_samples};")
    vhdl_code.append(f"    constant NUM_FEATURES : integer := {num_features};")
    vhdl_code.append("")

    # Type declarations
    vhdl_code.append("    -- Array type for features of a single sample")
    vhdl_code.append("    type feature_array_t is array (0 to NUM_FEATURES-1) of signed(15 downto 0);")
    vhdl_code.append("")
    vhdl_code.append("    -- Array type for all samples")
    vhdl_code.append("    type iris_features_t is array (0 to NUM_SAMPLES-1) of feature_array_t;")
    vhdl_code.append("")
    vhdl_code.append("    -- Array type for labels")
    vhdl_code.append("    type iris_labels_t is array (0 to NUM_SAMPLES-1) of signed(15 downto 0);")
    vhdl_code.append("")

    # Feature data constant
    vhdl_code.append("    -- Iris features in Q2.13 fixed-point format")
    vhdl_code.append("    constant IRIS_FEATURES : iris_features_t := (")

    for i in range(num_samples):
        # Start of sample array
        line = "        ("

        # Add all features for this sample
        feature_strs = []
        for j in range(num_features):
            value = features_q2_13[i, j]
            # Convert to signed 16-bit representation
            if value >= 0:
                hex_value = f'X"{value:04X}"'
            else:
                # Two's complement for negative values
                hex_value = f'X"{(value & 0xFFFF):04X}"'
            feature_strs.append(hex_value)

        line += ", ".join(feature_strs)
        line += ")"

        # Add comma if not last sample
        if i < num_samples - 1:
            line += ","

        vhdl_code.append(line)

    vhdl_code.append("    );")
    vhdl_code.append("")

    # Label data constant
    vhdl_code.append("    -- Iris labels in Q2.13 fixed-point format")
    vhdl_code.append("    -- 0 (X\"0000\") = Setosa, 8192 (X\"2000\") = Non-Setosa")
    vhdl_code.append("    constant IRIS_LABELS : iris_labels_t := (")

    # Format labels in rows of 5
    labels_per_row = 5
    for i in range(0, num_samples, labels_per_row):
        line = "        "

        # Get labels for this row
        row_labels = []
        for j in range(i, min(i + labels_per_row, num_samples)):
            value = labels_q2_13[j]
            hex_value = f'X"{value:04X}"'
            row_labels.append(hex_value)

        line += ", ".join(row_labels)

        # Add comma if not last row
        if i + labels_per_row < num_samples:
            line += ","

        vhdl_code.append(line)

    vhdl_code.append("    );")
    vhdl_code.append("")

    # End package
    vhdl_code.append("end package iris_dataset_small_pkg;")
    vhdl_code.append("")

    # Write to file
    with open(output_file, 'w') as f:
        f.write('\n'.join(vhdl_code))

    print(f"VHDL package generated: {output_file}")
    print(f"Number of samples: {num_samples}")
    print(f"Number of features: {num_features}")
    print(f"Label distribution: Setosa={np.sum(labels == 0)}, Non-Setosa={np.sum(labels == 1)}")


def main():
    """Main function to generate Iris VHDL package."""
    print("Loading Iris dataset...")

    # Load Iris dataset
    iris = load_iris()
    X = iris.data
    y = iris.target

    # Convert to binary classification (Setosa vs Non-Setosa)
    # Setosa = 0, Non-Setosa (Versicolor and Virginica) = 1
    y_binary = (y != 0).astype(int)

    # Take balanced samples: 15 Setosa (indices 0-14) + 15 Non-Setosa (indices 50-64)
    # This ensures we have both classes represented
    setosa_indices = np.arange(0, 15)  # First 15 Setosa samples
    non_setosa_indices = np.arange(50, 65)  # 15 Non-Setosa samples (Versicolor)
    selected_indices = np.concatenate([setosa_indices, non_setosa_indices])

    X_subset = X[selected_indices]
    y_subset = y_binary[selected_indices]

    # CRITICAL: Shuffle the data to prevent ordered training
    np.random.seed(42)  # For reproducibility
    shuffle_idx = np.random.permutation(len(X_subset))
    X_subset = X_subset[shuffle_idx]
    y_subset = y_subset[shuffle_idx]

    print(f"Selected {X_subset.shape[0]} samples")
    print(f"Features shape: {X_subset.shape}")
    print(f"Data shuffled. First 10 labels: {y_subset[:10]}")

    # Normalize features to [0, 1] range
    print("Normalizing features to [0, 1] range...")
    scaler = MinMaxScaler(feature_range=(0, 1))
    X_normalized = scaler.fit_transform(X_subset)

    # Print statistics
    print("\nFeature statistics (after normalization):")
    for i in range(X_normalized.shape[1]):
        print(f"  Feature {i}: min={X_normalized[:, i].min():.4f}, "
              f"max={X_normalized[:, i].max():.4f}, "
              f"mean={X_normalized[:, i].mean():.4f}")

    # Generate VHDL package
    print("\nGenerating VHDL package...")
    generate_vhdl_package(X_normalized, y_subset, 'iris_dataset_small_pkg.vhd')

    print("\nDone!")


if __name__ == "__main__":
    main()
